### ISSUE TITLE
How to disable z-index rebasing?

### ISSUE THREAD

**Issue by Fixluja** [tnottu/less-autocompile#7]
Hi Tomi,

how can I disable z-index rebasing in less-postcss-compile or switch to cssnano options.safe altogether? Is it possible?

Best regards

**Comment by tnottu** [comment]
Heya!

Passing options to cssnano isn't possible at this time, but it should be quite simple to change the code that it accepts `compress: safe` to enable safe mode.

I made a branch with a possible fix, but I didn't try it out yet :) It's been long time since I did anything to this plugin or Atom plugins in general, so I can't get into it right away.

If you want, you could try installing the [cssnano-safe](https://github.com/tnottu/less-postcss-autocompile/tree/cssnano-safe) branch as a local development package on your computer and see if the change works.

**Comment by Fixluja** [comment]
Hi Tomi,

I bow my head in awe! Your changes in lib/postcss-plugins.js plus "compress: safe" in my main.less did indeed work as expected. Thank you so much for your help!

Fixluja
